version: '3'
services:
  db:
    container_name: ivoryPay
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ivoryPayDev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/ivoryPay-data:/var/lib/postgresql/data
